#!/bin/bash
# Quick liveness check on candidate agency websites
candidates=(
  "https://www.pentagram.com"
  "https://droga5.com"
  "https://ueno.co"
  "https://humaan.com"
  "https://www.hugeinc.com"
  "https://www.rga.com"
  "https://bynd.com"
  "https://hellomonday.com"
  "https://neverland.agency"
  "https://loveandmoney.agency"
  "https://bff.co"
  "https://orangeyouglad.com"
  "https://reflektor.digital"
  "https://rno1.com"
  "https://themovetic.com"
  "https://cemtrexlabs.com"
  "https://www.loungelizard.com"
  "https://isadoradigitalagency.com"
  "https://akinsparker.com"
  "https://agence-belle-epoque.fr/en"
  "https://buzzworthystudio.com"
  "https://caavadesign.com"
  "https://www.tambien.studio"
  "https://www.leeroy.ca"
  "https://www.crftd.nl"
  "https://ninjapromo.io"
  "https://www.interodigital.com"
  "https://engagemassive.com"
  "https://madeinevolve.com"
  "https://redant.com.au"
  "https://mikmakstudio.com"
  "https://pixel-pink.de/en"
  "https://animalmade.com"
  "https://www.else.biz"
  "https://valentincheval.design"
  "https://movestudio.site"
  "https://www.spotcreates.com"
  "https://www.harvey.ai"
  "https://www.elevenlabs.io"
  "https://www.beautiful.ai"
)
for url in "${candidates[@]}"; do
  code=$(curl -s -o /dev/null -w "%{http_code}" -L --max-time 12 -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36" "$url" 2>/dev/null)
  echo "$code  $url"
done
